services:
  - type: web
    name: voyago-server
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: MONGO_URI
        sync: false
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: CLIENT_URL
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: OPENWEATHER_API_KEY
        sync: false
      - key: OPENTRIPMAP_API_KEY
        sync: false
      - key: EXCHANGERATE_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: RESEND_FROM
        sync: false