import React from 'react';
import LegalLayout from '../components/common/LegalLayout';

const sections = [
  {
    title: '1. Acceptance of Terms',
    body: 'By accessing or using Voyago, you agree to be bound by these Terms of Service and all applicable laws. If you do not agree, please do not use the service.',
  },
  {
    title: '2. Description of Service',
    body: 'Voyago is a travel research and planning assistant that provides estimated budgets, weather and safety information, and AI-generated itineraries. Estimates are informational and approximate â€” actual costs and conditions may vary.',
  },
  {
    title: '3. User Accounts',
    body: 'You are responsible for maintaining the confidentiality of your account credentials and for all activity under your account. You agree to provide accurate information when registering and to notify us of any unauthorised use.',
  },
  {
    title: '4. Not Financial or Booking Advice',
    body: 'Trip budget figures, prices, and availability are estimates only. We do not sell or guarantee bookings. When you follow links to external providers such as airlines, railways, or hotels, you are subject to those providers\' own terms and pricing.',
  },
  {
    title: '5. AI-Generated Content',
    body: 'Itineraries, packing lists, and chat responses are generated by artificial intelligence and may contain inaccuracies. Always verify important details â€” safety, entry fees, opening hours, and travel restrictions â€” with official sources before travelling.',
  },
  {
    title: '6. Acceptable Use',
    body: 'You agree not to misuse the service, attempt to disrupt it, harvest data at scale, or use it for any unlawful purpose. We may suspend accounts that violate these terms.',
  },
  {
    title: '7. Intellectual Property',
    body: 'Voyago branding, design, and original content are the property of Voyago. You may use the service for personal, non-commercial travel planning.',
  },
  {
    title: '8. Disclaimers & Limitation of Liability',
    body: 'The service is provided "as is" without warranties of any kind. To the fullest extent permitted by law, Voyago shall not be liable for any damages arising from use of the service, reliance on estimates, or AI-generated content.',
  },
  {
    title: '9. Changes to These Terms',
    body: 'We may revise these Terms at any time. Continued use after changes are posted constitutes acceptance of the updated Terms.',
  },
  {
    title: '10. Contact',
    body: 'For questions about these Terms, please reach out through the contact options available on our site.',
  },
];

export default function TermsPage() {
  return (
    <LegalLayout
      title="Terms of Service"
      updated="August 4, 2026"
      intro="The terms governing your use of the Voyago travel planning service."
    >
      {sections.map((s) => (
        <section key={s.title}>
          <h2 className="text-lg font-bold mb-2" style={{ color: 'var(--primary-light)' }}>{s.title}</h2>
          <p className="text-sm text-muted leading-relaxed">{s.body}</p>
        </section>
      ))}
    </LegalLayout>
  );
}